version: '3.8'
services:

  vault:
    image: hashicorp/vault:1.19.0
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "EeZGlSEjcD9rw5oOzV4W%"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault:/vault/file
    command: "server -dev -dev-root-token-id=EeZGlSEjcD9rw5oOzV4W%"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ~/Documents/keys/:/root/.ssh:ro
    environment:
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: "EeZGlSEjcD9rw5oOzV4W%"
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

volumes:
  vault:
    driver: local