version: '3.8'
services:

  vault:
    image: hashicorp/vault:1.19.0
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "EeZGlSEjcD9rw5oOzV4W%"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault:/vault/file
    command: "server -dev -dev-root-token-id=EeZGlSEjcD9rw5oOzV4W%"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - backend:/mnt/data
    environment:
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: "EeZGlSEjcD9rw5oOzV4W%"
      DOWNLOAD_DIR: "/mnt/data"
    ports:
      - "8000:8000"
    depends_on:
      - vault

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # volumes:
    #   - ./frontend:/app
    ports:
      - "3000:3000"

volumes:
  vault:
    driver: local
  backend:
    driver: local