# version: '3.8'
services:

  vault:
    image: hashicorp/vault:1.19.0
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    command: ["vault", "server", "-config=/vault/config/vault-config.json"]
    volumes:
      - vault:/vault/file
      - ./vault-config.json:/vault/config/vault-config.json:ro

  vault-init:
    build:
      context: ./vault-init
      dockerfile: Dockerfile
    depends_on:
      - vault
    volumes:
      - vault:/vault/file

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - backend:/mnt/data
      - vault:/vault/file:ro
    environment:
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN_FILE: "/vault/file/app_token"
      DOWNLOAD_DIR: "/mnt/data"
    ports:
      - "8000:8000"
    depends_on:
      - vault
      - vault-init

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

volumes:
  vault:
    driver: local
  backend:
    driver: local